### ISSUE TITLE
디스커스 댓글창 구현하기

### ISSUE THREAD

**Issue by BumgeunSong** [Jesscha/learningman#83]
- 독자들이 소셜 로그인해서 댓글 달 수 있도록 구현

**Comment by Jesscha** [comment]
이거 누군가의 disqus 계정으로 만들어야 하는데, 51% 범근 선생님으로 할지 그냥 내걸로 할지?

**Comment by Jesscha** [comment]
@cloudinertia

**Comment by Jesscha** [comment]
@cloudinertia 여유될 때 해주실 의향 있습니까?

**Comment by BumgeunSong** [comment]
@BumgeunSong 내 계정으로 하자. 가입하고 코드같은 걸 알려주면 되는건감

**Comment by Jesscha** [comment]
disqus 가입하고 아이디랑 비번 걍 알려주는 식은 어떨까? @BumgeunSong

**Comment by Jesscha** [comment]
@cloudinertia 가 맡아서 하기로 함
