### ISSUE TITLE
메인 페이지 UI 변경 (멤버별로 글 나뉘어 보이도록)

### ISSUE THREAD

**Issue by BumgeunSong** [Jesscha/learningman#84]
- 맨 위에 러닝맨 소개 멘트가 있음
- All / Essay / Challenge 같은 태그는 굳이 필요없어보임.
- 대신 각자 멤버 이름 및 아바타로 표현된 탭이 있음.
- 탭을 클릭하면 해당 멤버 목표 및 자기 소개가 적힌 글이 위에 보임.
- 그 밑으로 그 멤버가 그 동안 쓴 최신 글이 보여짐.

**Comment by Jesscha** [comment]
이슈가 섞여 있어서 close 하고 나누어서 마일스톤에 할당하겠습니다.

**Comment by Jesscha** [comment]
아바타 png 파일 구성후  공유 부탁 @BumgeunSong 
변화후 레이아웃 구성도 @BumgeunSong 이 맞아 주시나요?

**Comment by BumgeunSong** [comment]
@BumgeunSong 이미지 업로드했음 path : Contents > Asset

**Comment by BumgeunSong** [comment]
https://learningman.invisionapp.com/freehand/LearningMan-lhdbOxFHP

**Comment by Jesscha** [comment]
남은 할일 정리
- [ ] 홈 화면 맴버 렌덤 포커싱
- [ ] 멤버별 태그 디자인 변경 
- [ ] 홈 화면 자기소개 컴포넌트 디자인 및 적용
- [ ] 콘텐츠 화면 상단 저자 컴포넌트 디자인 및 적용
- [ ] 콘텐츠 화면 하단에 자기소개 컴포넌트 적용하기

**Comment by Jesscha** [comment]
- [ ] og 이미지 제대로 가는지 확인 필요함
- [ ] 모바일 홈 최상단 이미지 배치 어떻게 할지

**Comment by Jesscha** [comment]
이슈, 작가가 아닌 태그로 접근하는 경우 화면이 어떻게 나올지 정의된 바 없음
